name: Build Tauri App

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install dependencies
        run: yarn install

      - name: Install NSIS for Windows bundling
        run: choco install nsis

      - name: Build Tauri app
        run: yarn tauri build

      - name: Check output (debug)
        run: dir src-tauri\\target\\release\\bundle /s

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: src-tauri/target/release/bundle/windows
          if-no-files-found: warn
